# Generated by Django 4.2.30 on 2026-06-09 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_bill_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.prescription'),
        ),
    ]
