# Generated by Django 4.2.30 on 2026-06-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_bill_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='doctor_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
