# Generated by Django 4.2.30 on 2026-06-19 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_bill_doctor_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_reopened',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='parent_appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups', to='appointments.appointment'),
        ),
    ]
