# Generated by Django 4.2.30 on 2026-06-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_remove_appointment_doctor_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='doctor_fee',
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
