# Generated by Django 4.2.30 on 2026-06-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_remove_prescription_doctor_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='is_billed',
            field=models.BooleanField(default=False),
        ),
    ]
