# Generated by Django 4.2.30 on 2026-06-30 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_prescription_is_billed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='doctor_fee',
        ),
    ]
