# Generated by Django 4.2.30 on 2026-06-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_remove_bill_doctor_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='medicine_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
