# Generated by Django 4.2.30 on 2026-06-30 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_bill_medicine_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='is_billed',
        ),
    ]
