# Generated by Django 4.2.30 on 2026-06-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
